[workspace]
members = [ "vcpkg", "vcpkg_cli", "cargo-vcpkg" ]
exclude = [ "systest", "tests" ]

# [patch.crates-io]
# vcpkg = { path = 'vcpkg' }

# [patch.'https://github.com/mcgoo/vcpkg-rs']
# vcpkg = { path = 'vcpkg' }
